### ISSUE TITLE
X86 Runtime

### ISSUE THREAD

**Issue by azhkprtw** [nsbasic-archive/NS-Basic-for-WinCE#1]
Hi, I was wondering how it would be possible to compile an x86 Windows CE runtime ?
Is there a certain source file I need to locate to do this?
I have all of the major IDEs installed so that wouldn't be an issue for me. 
I don't need the NS Basic program to develop on device. Just wanted an ability to execute previously developed programs on Windows CE

**Comment by gwhenne** [comment]
I'm sorry - it has been so many years since anyone here worked with this that we have no recollection whatsoever of the details.

**Comment by azhkprtw** [comment]
Hey no worries! I completely understand. Thanks for the quick follow up though ! Have a great week
